-- ==========================================================================
-- Chitrawan Nature Cure Hospital — COMPLETE DATABASE (schema + default content)
--
-- ONE FILE. ONE IMPORT. The site works immediately after importing — no seed
-- script needed. All content is editable later from the admin panel (/admin).
--
--   Local XAMPP : start MySQL, open http://localhost/phpmyadmin → Import →
--                 choose this file → Go        (or: mysql -u root < database.sql)
--   cPanel      : create the database first, then import this file.
--
-- Default admin login — CHANGE THE PASSWORD after the first login!
--     URL:      {your-site}/admin
--     Username: admin
--     Password: Admin@Chitrawan2026
--
-- ⚠ To change the default content: edit app/data/*.php, then re-seed with
--   php app/scripts/seed.php  (the seed script always matches this file).
-- ==========================================================================
CREATE DATABASE IF NOT EXISTS `wellness`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `wellness`;

-- ==========================================================================
-- 1. SCHEMA — all tables
-- ==========================================================================

-- ---------------------------------------------------------------
-- Appointment bookings (submitted through the Contact page form)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS appointments (
    id          CHAR(16)     NOT NULL,
    name        VARCHAR(120) NOT NULL,
    email       VARCHAR(190) NOT NULL,
    phone       VARCHAR(40)  NOT NULL DEFAULT '',
    treatment   VARCHAR(120) NOT NULL DEFAULT '',
    date        VARCHAR(20)  NOT NULL DEFAULT '',
    time        VARCHAR(20)  NOT NULL DEFAULT '',
    message     TEXT         NULL,
    status      ENUM('new', 'confirmed', 'rejected', 'completed') NOT NULL DEFAULT 'new',
    created_at  DATETIME     NOT NULL,
    PRIMARY KEY (id),
    KEY idx_created_at (created_at),
    KEY idx_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Advance payments via QR code (submitted through the Tariff page)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qr_payments (
    id             CHAR(16)     NOT NULL,
    name           VARCHAR(120) NOT NULL,
    email          VARCHAR(190) NOT NULL,
    phone          VARCHAR(40)  NOT NULL DEFAULT '',
    address        VARCHAR(300) NOT NULL DEFAULT '',
    package        VARCHAR(120) NOT NULL DEFAULT '',
    amount         VARCHAR(40)  NOT NULL DEFAULT '',
    transaction_id VARCHAR(120) NOT NULL DEFAULT '',
    message        TEXT         NULL,
    screenshot     VARCHAR(300) NOT NULL DEFAULT '',
    status         ENUM('new', 'verified', 'rejected') NOT NULL DEFAULT 'new',
    created_at     DATETIME     NOT NULL,
    PRIMARY KEY (id),
    KEY idx_created_at (created_at),
    KEY idx_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Therapy pages (one row per therapy, content JSON-encoded)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS therapies (
    id          INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,  -- numeric id for the admin content manager
    slug        VARCHAR(80)  NOT NULL,
    category    VARCHAR(40)  NOT NULL,
    title       VARCHAR(120) NOT NULL,
    icon        VARCHAR(40)  NOT NULL DEFAULT 'icon-leaf',
    image       VARCHAR(300) NOT NULL DEFAULT '',
    intro       TEXT         NULL,
    about       TEXT         NULL,   -- JSON array of paragraphs
    methods     TEXT         NULL,   -- JSON array
    benefits    TEXT         NULL,   -- JSON array
    PRIMARY KEY (slug),
    KEY idx_category (category)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Blog posts (one row per article, content JSON-encoded)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS posts (
    slug        VARCHAR(80)  NOT NULL,
    title       VARCHAR(160) NOT NULL,
    category    VARCHAR(40)  NOT NULL DEFAULT 'Wellness',
    date        VARCHAR(30)  NOT NULL DEFAULT '',
    image       VARCHAR(300) NOT NULL DEFAULT '',
    excerpt     TEXT         NULL,
    content     TEXT         NULL,   -- JSON array of {h, p} sections
    key_points  TEXT         NULL,   -- JSON array
    PRIMARY KEY (slug)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Gallery media items (/gallery page)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gallery (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(160) NOT NULL,
    description TEXT         NULL,
    image       VARCHAR(300) NOT NULL DEFAULT '',
    alt         VARCHAR(200) NOT NULL DEFAULT '',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Patient testimonials (home page)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS testimonials (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    role        VARCHAR(120) NOT NULL DEFAULT '',
    initials    VARCHAR(8)   NOT NULL DEFAULT '',
    avatar      VARCHAR(8)   NOT NULL DEFAULT 'a1',
    rating      TINYINT      NOT NULL DEFAULT 5,
    quote       TEXT         NULL,
    status      ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Team members (About page, "Our Group" section)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    role        VARCHAR(160) NOT NULL DEFAULT '',
    image       VARCHAR(300) NOT NULL DEFAULT '',
    initials    VARCHAR(8)   NOT NULL DEFAULT '',
    avatar      VARCHAR(8)   NOT NULL DEFAULT 'a1',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Tariff: membership-style packages (/tariff page)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tariff_plans (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description TEXT         NULL,
    price       VARCHAR(20)  NOT NULL DEFAULT '',
    period      VARCHAR(30)  NOT NULL DEFAULT '',
    features    TEXT         NULL,   -- JSON array of strings
    featured    TINYINT(1)   NOT NULL DEFAULT 0,
    badge       VARCHAR(60)  NOT NULL DEFAULT '',
    cta_label   VARCHAR(60)  NOT NULL DEFAULT 'Book a Session',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Tariff: individual service rate card (/tariff page)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tariff_services (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    service     VARCHAR(160) NOT NULL,
    duration    VARCHAR(40)  NOT NULL DEFAULT '',
    price       VARCHAR(20)  NOT NULL DEFAULT '',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- "Why Choose Us" feature cards (home page photo carousel)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS features (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(160) NOT NULL,
    description TEXT         NULL,
    image       VARCHAR(300) NOT NULL DEFAULT '',
    icon        VARCHAR(40)  NOT NULL DEFAULT 'icon-leaf',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- "What We Offer" service cards (home page photo carousel)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS offers (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(160) NOT NULL,
    description TEXT         NULL,
    image       VARCHAR(300) NOT NULL DEFAULT '',
    icon        VARCHAR(40)  NOT NULL DEFAULT 'icon-leaf',
    link        VARCHAR(200) NOT NULL DEFAULT '/treatments',
    sort_order  INT          NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Admin panel users (usernames + passwords, managed from the admin panel)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
    id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email         VARCHAR(190) NOT NULL DEFAULT '',
    username      VARCHAR(60)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL DEFAULT '',
    role          ENUM('admin', 'staff') NOT NULL DEFAULT 'admin',
    created_at    DATETIME     NOT NULL,
    updated_at    DATETIME     NOT NULL,
    UNIQUE KEY uq_admin_username (username)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Editable page sections (per-page, per-section content)
-- Each row = one section of one page (e.g. home/hero, about/founder).
-- Field names are fixed; `extras` stores a JSON array of lines used for
-- checklists, stats, buttons, doctor cards, etc.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS page_sections (
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    page_key     VARCHAR(60)  NOT NULL,
    section_key  VARCHAR(80)  NOT NULL,
    kicker       VARCHAR(200) NOT NULL DEFAULT '',
    heading      VARCHAR(300) NOT NULL DEFAULT '',
    content      TEXT         NULL,
    sub_content  TEXT         NULL,
    image        VARCHAR(300) NOT NULL DEFAULT '',
    media        VARCHAR(300) NOT NULL DEFAULT '',
    link         VARCHAR(300) NOT NULL DEFAULT '',
    link_label   VARCHAR(160) NOT NULL DEFAULT '',
    extras       TEXT         NULL,
    UNIQUE KEY uq_page_section (page_key, section_key)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ==========================================================================
-- 2. DEFAULT CONTENT (kept in sync with app/data/*.php via seed.php)
-- ==========================================================================

-- Therapies (23) — REPLACE = safe to re-import, keeps other rows
REPLACE INTO therapies (slug, category, title, icon, image, intro, about, methods, benefits) VALUES
('naturopathy', '/treatments', 'Naturopathy', 'icon-leaf', '/wellness/public/uploads/photos/photo-1519823551278-64ac92734fb1.jpg', 'A natural healthcare system that helps your body heal itself through gentle, drug-free methods.', '["Naturopathy is a complete system of natural medicine built on the belief that the body has an innate ability to heal itself. Instead of suppressing symptoms, our naturopaths work to remove the causes of illness and restore balance through water, earth, heat, herbs, and wholesome food.","Every program begins with a detailed health assessment, after which our team designs a personal treatment plan combining therapies that detoxify, strengthen immunity, and re-energize your body&rsquo;s own healing power."]', '[{"title":"Hydrotherapy","definition":"Water, in all its forms — warm baths, cool compresses, wraps and jets — is used at precise temperatures to boost circulation, calm pain and support the body\'s natural detoxification, one of the oldest and most effective natural medicines."},{"title":"Mud therapy","definition":"Mineral-rich mud is applied over the skin to absorb impurities, draw out heat and soothe inflammation. As the mud dries it gently pulls congestion away from the body, calming digestion and easing joint and muscle discomfort."},{"title":"Herbal therapy","definition":"Selected herbs, teas and natural extracts are matched to your constitution to support immunity, digestion and rest. Herbal remedies work gently with your body to restore balance without the side effects of synthetic medicines."},{"title":"Massage therapy","definition":"Hands-on therapeutic massage relaxes tight muscles, improves blood and lymphatic flow, and releases deeply held tension. It is a powerful way to relieve stress, ease pain and wake up the body\'s own healing response."},{"title":"Steam therapy","definition":"Warm herbal steam opens the pores, loosens congestion and encourages gentle sweating — the body\'s natural way of releasing impurities. Regular steam sessions refresh the skin, relax the nerves and support the respiratory system."},{"title":"Detoxification programs","definition":"A guided, multi-day cleanse that combines diet, hydration, rest and supportive therapies to help the body eliminate accumulated toxins. Each program is personalized and carefully supervised so the process is safe, gentle and effective."}]', '["Supports the body&rsquo;s natural self-healing","Helps detoxify and cleanse the system","Strengthens immunity and vitality","Reduces dependence on medication","Improves long-term energy balance"]'),
('yoga-therapy', '/treatments', 'Yoga Therapy', 'icon-moon', '/wellness/public/uploads/photos/photo-1558618666-fcd25c85cd64.jpg', 'Physical postures, breathing, and meditation woven together to restore body and mind.', '["Yoga therapy applies the ancient science of yoga as a personalized therapeutic tool. Led by certified instructors, sessions combine gentle postures, controlled breathing, and guided meditation to address everything from stress and posture to chronic pain.","Whether you are a beginner or an experienced practitioner, each session is adapted to your body and goals — helping you move with ease, breathe more freely, and find a calmer, more balanced state of mind."]', '[{"title":"Hatha Yoga","definition":"A classical, gentle style of yoga that pairs physical postures with steady breathing. It stretches and strengthens the body slowly and safely, making it ideal for beginners and for restoring calm."},{"title":"Pranayama (breathwork)","definition":"Controlled breathing exercises that calm the nervous system and increase oxygen flow. Practiced daily, they reduce stress, steady the heart and clear the mind."},{"title":"Guided meditation","definition":"A therapist-led practice that carries you into deep relaxation, easing the busy mind. Regular sessions reduce anxiety, improve sleep and build lasting inner calm."},{"title":"Stress management","definition":"Practical yoga-based tools — breathing, movement and mindfulness — that lower stress hormones and build resilience. You learn to recognize tension early and release it before it builds."},{"title":"Flexibility training","definition":"Progressive stretching routines that lengthen tight muscles and improve joint range of motion. Over time, everyday movement becomes easier, freer and more comfortable."},{"title":"Weight management","definition":"A balanced approach that combines mindful movement, better breathing and healthy habits. It supports natural weight loss, boosts metabolism and helps you keep results long-term."}]', '["Increases flexibility and strength","Calms the mind and reduces anxiety","Improves breathing and circulation","Supports healthy weight management","Cultivates lasting inner peace"]'),
('acupuncture', '/treatments', 'Acupuncture', 'icon-zap', '/wellness/public/uploads/photos/photo-1544161515-4ab6ce6db874.jpg', 'Fine needles and precise points that restore the flow of energy and ease pain.', '["Acupuncture is a time-honored therapy that stimulates specific points on the body to restore the smooth flow of energy (Qi). Thin, sterile needles are gently inserted at these points, encouraging the body to release tension, reduce inflammation, and switch on its own healing response.","Our practitioners use a gentle, modern approach to acupuncture, making each session comfortable and effective — whether you come for persistent pain, stress, or simply to rebalance your system."]', '[{"title":"Fine needle therapy","definition":"Ultra-thin, sterile needles are gently placed at precise points on the body to restore the smooth flow of energy (Qi). The insertion is barely felt, yet it can reduce pain, release tension and switch on the body\'s healing response."},{"title":"Moxibustion (heat therapy)","definition":"A warming herbal preparation (moxa) is burned close to the skin over specific points, gently heating them to stimulate circulation and energy flow. It is especially helpful for cold, sluggish conditions and deep-seated aches."},{"title":"Cupping therapy","definition":"Silicone or glass cups are placed on the skin to create gentle suction, lifting the tissues to boost blood flow and loosen tight muscles. The result is deep relief, especially for the back and shoulders."},{"title":"Electro-acupuncture","definition":"A mild, comfortable electrical pulse is passed through the needles to amplify the stimulation at each point. It is particularly effective for stubborn pain and for re-energizing tired muscles."},{"title":"Meridian assessment","definition":"Before treatment begins, the practitioner maps the body\'s energy pathways to find where flow is blocked. This diagnosis shapes every treatment, so each session targets the true root of your complaint."}]', '["Effective relief from back and neck pain","Eases migraines and tension headaches","Calms anxiety and improves sleep","Supports joint health in arthritis","Restores smooth energy flow"]'),
('physical-therapy', '/physiotherapy', 'Physical Therapy', 'icon-activity', '/wellness/public/uploads/photos/photo-1571019613454-1cb2f99b2d8b.jpg', 'Guided exercise and manual therapy that rebuild strength, mobility, and function.', '["Physical therapy helps you move better, feel stronger, and live without pain. Our physiotherapists assess how your body moves, then guide you through targeted exercises and hands-on techniques that restore strength, flexibility, and confidence.","From recovering after an injury to improving everyday movement, every plan is personal — so you progress safely and see lasting results."]', '[{"title":"Manual therapy","definition":"Hands-on techniques applied by your physiotherapist — including joint mobilization, soft-tissue release and therapeutic massage — that loosen tight muscles, improve joint movement and reduce pain without medication."},{"title":"Therapeutic exercises","definition":"A personalized set of strengthening and stabilization exercises prescribed to rebuild muscle power, endurance and control in the areas that need it most, progressing safely at your own pace."},{"title":"Stretching and mobility work","definition":"Guided stretching routines that restore flexibility and range of motion to stiff muscles and joints, making everyday movements easier and more comfortable."},{"title":"Gait and balance training","definition":"Exercises that improve the way you walk and stand — strengthening stability, correcting your walking pattern and reducing the risk of falls."},{"title":"Home exercise programs","definition":"A simple routine you continue between sessions, with clear instructions and checkpoints, so your recovery keeps progressing even when you are not at the center."}]', '["Restores strength and mobility","Reduces pain and stiffness","Improves posture and balance","Speeds recovery from injury","Prevents future problems"]'),
('electrotherapy', '/physiotherapy', 'Electrotherapy', 'icon-zap', '/wellness/public/uploads/photos/photo-1576091160399-112ba8d25d1d.jpg', 'Modern electrical stimulation that reduces pain and accelerates the body\'s healing.', '["Electrotherapy uses safe, targeted electrical currents to relieve pain, reduce swelling, and stimulate muscles and tissues that need to heal. It is a highly effective complement to hands-on therapy for both acute injuries and chronic conditions.","Our therapists choose the most suitable modality for your condition and adjust intensity to keep every session comfortable and effective."]', '[{"title":"TENS for pain relief","definition":"Transcutaneous Electrical Nerve Stimulation uses gentle, low-intensity electrical pulses through small pads placed on the skin to interrupt pain signals and encourage the body\'s own natural pain relief — a drug-free way to manage both acute and chronic pain."},{"title":"Ultrasound therapy","definition":"Therapeutic ultrasound sends high-frequency sound waves deep into soft tissues, generating gentle warmth that speeds up healing, reduces inflammation and eases pain in muscles, tendons and ligaments."},{"title":"Interferential therapy","definition":"Two mid-frequency currents are crossed at the treatment area to deliver a deep, comfortable stimulation that reaches painful joints and muscles, helping to reduce swelling and relax spasms."},{"title":"Muscle stimulation","definition":"Controlled electrical impulses are applied directly to weakened or recovering muscles, causing safe, gentle contractions that rebuild strength and prevent muscle wasting after injury or surgery."},{"title":"Heat and cold modalities","definition":"Simple but powerful — targeted heat relaxes stiff muscles and boosts circulation, while cold reduces acute swelling and numbs pain; your therapist applies the right one for each stage of healing."}]', '["Quick, effective pain relief","Reduces swelling and inflammation","Stimulates muscle recovery","Accelerates tissue healing","Drug-free treatment option"]'),
('rehabilitation-therapy', '/physiotherapy', 'Rehabilitation Therapy', 'icon-heart', '/wellness/public/uploads/photos/photo-1571019614242-c5c5dee9f50b.jpg', 'Structured programs that guide you back to full function after injury, surgery, or illness.', '["Rehabilitation therapy is your roadmap back to an active life. Whether you are recovering from surgery, a sports injury, a stroke, or a neurological condition, our therapists build a step-by-step program that rebuilds strength, balance, and independence.","We track your progress closely and adjust the plan as you improve — so you recover at the right pace, without setbacks."]', '[{"title":"Post-injury rehabilitation","definition":"A structured, phased program that guides you from the day of injury back to full activity — protecting the area first, then progressively rebuilding strength, mobility and confidence."},{"title":"Post-surgical recovery","definition":"A closely supervised recovery plan designed around your procedure, restoring range of motion, strength and function safely so you heal well and avoid complications."},{"title":"Neurological rehabilitation","definition":"Specialist therapy for conditions affecting the brain and nervous system — such as stroke or Parkinson\'s — that retrains movement, balance, coordination and daily skills to maximize independence."},{"title":"Sports recovery programs","definition":"Sport-specific conditioning that gets athletes back on the field faster and stronger, with drills and strengthening matched to the demands of their sport and a clear plan to prevent re-injury."},{"title":"Balance and coordination training","definition":"Targeted exercises that retrain the body\'s balance systems, improving stability, reaction and control — essential after injury, for older adults, and for anyone wanting to move with confidence."}]', '["Faster, safer recovery","Restores independence and confidence","Rebuilds strength and coordination","Prevents re-injury","Personalized, closely supervised care"]'),
('postural-therapy', '/physiotherapy', 'Postural Therapy', 'icon-shield', '/wellness/public/uploads/photos/photo-1552693673-1bf958298935.jpg', 'Correct alignment and ergonomic guidance that relieve the strain of modern life.', '["Hours at desks and screens take a toll on posture — and posture takes a toll on your whole body. Postural therapy identifies the imbalances behind your aches, then uses targeted correction, strengthening, and practical ergonomic advice to bring your body back into alignment.","The result is less tension, fewer headaches, and a more comfortable, confident posture that lasts."]', '[{"title":"Posture assessment","definition":"A detailed analysis of how you stand, sit and move, identifying the muscle imbalances and habits behind your aches before a single correction is made."},{"title":"Muscle balancing","definition":"Gentle techniques that release overworked, tight muscles and re-awaken weak ones, restoring the natural balance that holds your body in good alignment."},{"title":"Core strengthening","definition":"Focused exercises that build the deep core muscles supporting your spine, so good posture becomes effortless rather than something you have to force."},{"title":"Ergonomic guidance","definition":"Practical advice for your work and home setup — chair height, screen position, desk layout — that removes the everyday strain feeding your posture problems."},{"title":"Desk and screen habit coaching","definition":"Simple habit changes for long hours at desks and phones — micro-breaks, repositioning cues and daily routines that keep your new posture from slipping away."}]', '["Relieves neck, shoulder, and back tension","Improves alignment and balance","Reduces screen-related strain","Prevents posture-related pain","Builds a stronger core"]'),
('fitness-therapy', '/physiotherapy', 'Fitness Therapy', 'icon-sun', '/wellness/public/uploads/photos/photo-1571902943202-507ec2618e8f.jpg', 'Customized exercise programs that build fitness around your body and goals.', '["Fitness therapy treats exercise like medicine — prescribed to your exact needs. Rather than a one-size-fits-all gym routine, our therapists design a program that builds strength, stamina, and flexibility safely, whatever your starting point.","Ideal for anyone who wants to get fitter, manage a condition, or simply feel more capable in daily life."]', '[{"title":"Custom exercise programs","definition":"An exercise plan built around your body, goals and current fitness level — nothing generic, everything prescribed to the way you move and what you want to achieve."},{"title":"Strength training","definition":"Progressive resistance work that builds functional muscle power safely, making daily activities easier and protecting your joints and bones."},{"title":"Endurance conditioning","definition":"Cardiovascular training designed to build stamina step by step, improving your heart and lung fitness at a pace your body can comfortably sustain."},{"title":"Flexibility sessions","definition":"Structured stretching that keeps muscles long and joints free, improving range of motion and reducing the stiffness that comes with age and inactivity."},{"title":"Progress tracking","definition":"Regular measurements and check-ins so you can see real improvements — and your therapist can adjust the program as you get stronger."}]', '["Improves overall fitness and stamina","Builds functional strength","Supports healthy weight","Boosts energy and mood","Safe for all fitness levels"]'),
('cardiovascular-endurance-training', '/physiotherapy', 'Cardiovascular & Endurance Training', 'icon-wind', '/wellness/public/uploads/photos/photo-1534438327276-14e5300c3a48.jpg', 'Heart-smart exercise programs that build stamina and protect your cardiovascular health.', '["A stronger heart means more energy for everything you love. Our endurance programs use heart-rate-guided aerobic training to safely build your cardiovascular fitness — from gentle conditioning to more advanced interval work.","Every session is monitored and adjusted to your capacity, making this program ideal for improving stamina, managing heart-health risk factors, and feeling more energetic."]', '[{"title":"Aerobic conditioning","definition":"Continuous, moderate-intensity exercise that steadily strengthens your heart and lungs, building a foundation of stamina you can feel in daily life."},{"title":"Interval training","definition":"Alternating bursts of higher effort with easier recovery periods — an efficient way to improve fitness faster, carefully dosed to your capacity."},{"title":"Heart-rate-guided sessions","definition":"Training zones set from your individual heart-rate response, so every session works the right intensity for your body — safe, effective and never guessing."},{"title":"Breathing and pacing techniques","definition":"Methods to keep your breathing steady and your effort controlled during exercise, improving efficiency and helping you go further with less fatigue."},{"title":"Recovery and rest management","definition":"Structured rest and recovery guidance — because the body adapts and grows stronger during recovery, not only during the workout itself."}]', '["Strengthens heart and lungs","Builds stamina and endurance","Improves circulation","Supports healthy blood pressure","Increases daily energy"]'),
('xone-exercise', '/physiotherapy', 'Xone Exercise', 'icon-activity', '/wellness/public/uploads/photos/photo-1543269865-cbf427effbad.jpg', 'Advanced exercise techniques for flexibility, mobility, and deep muscle strengthening.', '["Xone Exercise is a modern training approach that combines advanced movement patterns with targeted strengthening. It focuses on mobility, flexibility, and activating the deep muscles that support everyday movement and athletic performance.","Our therapists guide you through precise, progressive movements — perfect for athletes, active adults, and anyone looking to move with more freedom."]', '[{"title":"Advanced movement patterns","definition":"Precise, multi-joint movements that teach your body to move as one coordinated unit — improving the quality of everyday and athletic movement."},{"title":"Mobility and flexibility work","definition":"Targeted drills that expand your usable range of motion, releasing tightness so you can move freely and powerfully without restriction."},{"title":"Deep muscle activation","definition":"Exercises that switch on the deep stabilizer muscles around your joints — the foundations that support every stronger movement you make."},{"title":"Progressive strengthening","definition":"A step-by-step strengthening system that loads the muscles progressively, building real functional strength without overloading joints."},{"title":"Athletic conditioning","definition":"Sport-specific power, speed and agility work that translates strength into performance — for athletes and active adults alike."}]', '["Enhances flexibility and range of motion","Builds deep, functional strength","Improves movement quality","Supports athletic performance","Reduces injury risk"]'),
('therapeutic-fasting', '/diet-therapy', 'Therapeutic Fasting', 'icon-droplet', '/wellness/public/uploads/photos/photo-1599447421416-3414500d18a5.jpg', 'A medically supervised fasting program that resets digestion and detoxifies the body.', '["Therapeutic fasting gives your digestive system a well-deserved rest while the body turns inward to cleanse and repair. Under close supervision, fasting is a powerful tool for detoxification, improving metabolism, and breaking unhealthy food habits.","Our programs are always personalized and medically supervised — you are guided through every phase, from preparation to a gentle, nourishing reintroduction of food."]', '[{"title":"Medically supervised fasting","definition":"Your fast is guided and monitored by trained professionals, who track your energy, hydration and wellbeing throughout. Supervision makes the cleanse safe, comfortable and effective."},{"title":"Juice and water fasting plans","definition":"Fresh vegetable and fruit juices, herbal teas and pure water nourish the body while giving digestion a complete rest. Plans are tailored to your constitution so you stay energized while you cleanse."},{"title":"Gradual food reintroduction","definition":"Breaking a fast is as important as the fast itself. Simple, easy-to-digest foods are added back slowly, so your system adjusts gently and the benefits of the cleanse are locked in."},{"title":"Detox support therapies","definition":"Massage, steam and mud therapies are combined with fasting to help the body release impurities through the skin and lymphatic system. They make the cleanse deeper, gentler and more comfortable."},{"title":"Personalized guidance throughout","definition":"Every phase — preparation, fasting and reintroduction — is planned around your needs and reviewed with you. You are never alone: your team adjusts the plan as your body responds."}]', '["Supports natural detoxification","Improves digestion and metabolism","Breaks unhealthy eating habits","Boosts energy and mental clarity","Safe, closely supervised program"]'),
('raw-diet-therapy', '/diet-therapy', 'Raw Diet Therapy', 'icon-leaf', '/wellness/public/uploads/photos/photo-1512621776951-a57141f2eefd.jpg', 'Fresh, living foods rich in enzymes that energize and gently heal the body.', '["A raw food diet is rich in the enzymes, vitamins, and living energy that cooking can destroy. Our nutritionists design delicious raw meal plans using fresh fruits, vegetables, sprouts, and nuts that support healing and natural vitality.","Raw diet therapy is introduced gradually and balanced to suit your body — making it sustainable and enjoyable, not extreme."]', '[{"title":"Fresh fruit meals","definition":"Seasonal fruits, served whole or freshly prepared, deliver living enzymes, vitamins and natural sugars in their most vital form. They energize the body and support gentle cleansing."},{"title":"Raw vegetable dishes","definition":"Colorful salads, cold soups and grated vegetables preserve the nutrients and enzymes that cooking destroys. They are rich in fiber, keeping digestion regular and the body well-nourished."},{"title":"Sprouting and soaking","definition":"Grains, seeds and legumes are soaked and sprouted to unlock their nutrients and make them easier to digest. Sprouting boosts vitamins and enzymes while reducing anti-nutrients."},{"title":"Nuts, seeds, and superfoods","definition":"Raw nuts, seeds and nutrient-dense superfoods add healthy fats, protein and minerals to a raw diet. They keep meals satisfying and support skin, brain and heart health."},{"title":"Gradual transition guidance","definition":"Moving to a raw diet is done step by step so your digestion adapts comfortably. Your nutritionist plans the transition around your routine and preferences, making it sustainable, not extreme."}]', '["Preserves natural enzymes and nutrients","Boosts energy and vitality","Supports healthy weight loss","Improves skin and digestion","Gently detoxifies the body"]'),
('bland-food-therapy', '/diet-therapy', 'Bland Food Therapy', 'icon-heart', '/wellness/public/uploads/photos/photo-1505751172876-fa1923c5c528.jpg', 'Simple, gentle meals that soothe the digestive system and support recovery.', '["When the digestive system is sensitive, the answer is simplicity. Bland food therapy provides easy-to-digest, low-irritation meals that let your stomach and intestines rest, recover, and rebalance.","It is especially helpful for digestive complaints, during recovery from illness, and as part of detox programs. Our nutritionists keep the meals nutritious and varied — gentle on the stomach, never boring."]', '[{"title":"Easy-to-digest cooked meals","definition":"Softly cooked grains, vegetables and light proteins are prepared simply to reduce strain on the digestive tract. Gentle cooking releases nutrients while keeping the stomach calm."},{"title":"Soothing soups and porridges","definition":"Warm, smooth soups and porridges coat and comfort the digestive lining, easing irritation and supporting recovery. They are easy to absorb and deeply nourishing."},{"title":"Small, frequent meals","definition":"Eating smaller portions more often keeps the digestive system working steadily without overload. This reduces bloating, indigestion and post-meal fatigue."},{"title":"Low-irritation food choices","definition":"Spicy, fried, acidic and heavily processed foods are set aside in favor of mild, wholesome options. Removing irritants lets an inflamed gut rest and repair."},{"title":"Personalized meal rotation","definition":"Meals are rotated and varied so the diet stays nutritious and never boring. Your nutritionist adjusts the plan as your digestion improves."}]', '["Soothes sensitive digestion","Supports gut recovery","Reduces bloating and discomfort","Nutritious yet gentle","Ideal support during detox"]'),
('natural-botanicals', '/diet-therapy', 'Natural Botanicals', 'icon-sun', '/wellness/public/uploads/photos/photo-1466692476868-aef1dfb1e735.jpg', 'Herbs and botanicals used with care to support balance and natural healing.', '["For centuries, plants have been our most reliable medicine. Our team blends the wisdom of herbal tradition with modern safety standards, using teas, tinctures, and botanical remedies to support immunity, digestion, and calm.","Every botanical is chosen for your specific constitution and condition, and always reviewed alongside your overall wellness plan."]', '[{"title":"Herbal teas and infusions","definition":"Gently brewed teas from leaves, flowers and roots deliver plant medicine in a warm, soothing form. They are a simple daily way to support digestion, immunity and restful sleep."},{"title":"Tinctures and extracts","definition":"Concentrated herbal extracts capture the active compounds of plants in a few drops. They are potent, easy to dose and quickly absorbed, ideal for more targeted support."},{"title":"Traditional herbal remedies","definition":"Time-tested formulas passed down through generations bring proven relief for common ailments. They are blended with care and reviewed for safety alongside your wellness plan."},{"title":"Botanical supplements","definition":"Carefully sourced plant-based supplements provide concentrated nutrition where the diet falls short. Each one is chosen for purity and potency, and checked against your overall health picture."},{"title":"Personalized herbal blends","definition":"Herbs are selected specifically for your constitution, condition and goals. A personalized blend works far better than a one-size-fits-all remedy."}]', '["Supports immune health","Calms digestion and nerves","Offers natural, gentle remedies","Complements other therapies","Chosen for your specific needs"]'),
('organic-farm-produce', '/diet-therapy', 'Organic Farm Produce', 'icon-shield', '/wellness/public/uploads/photos/photo-1498837167922-ddd27525d352.jpg', 'Chemical-free fruits and vegetables, fresh from the farm to your plate.', '["Healing begins with clean food. We source fresh, chemical-free fruits and vegetables — much of it from our own organic farm — so every meal is as pure and nourishing as possible.","From farm to table, our kitchen turns these wholesome ingredients into healing meals that support every diet program we offer."]', '[{"title":"Chemical-free farm produce","definition":"Fruits and vegetables grown without synthetic pesticides, herbicides or fertilizers. Clean, pure produce gives the body the nourishment it needs to heal without added chemical burden."},{"title":"Freshly harvested daily","definition":"Produce is picked at peak ripeness and served the same day, when flavor and nutrients are at their highest. Fresh food simply tastes better and nourishes more deeply."},{"title":"Seasonal menu planning","definition":"Meals follow nature\'s calendar, using what grows best in each season. Seasonal eating is more nutritious, more flavorful and gentler on the environment."},{"title":"Farm-to-table meals","definition":"From the farm straight to the table, meals are prepared from whole ingredients with minimal processing. This short journey preserves nutrients and keeps food alive and nourishing."},{"title":"Support for garden therapy","definition":"Working with plants and soil is itself a healing practice. Gentle time in the garden reduces stress, improves mood and reconnects you with the source of your food."}]', '["Free from harmful chemicals","Higher in natural nutrients","Better taste and freshness","Supports sustainable farming","The purest foundation for healing"]'),
('salt-glow-massage', '/special-therapies', 'Salt Glow Massage', 'icon-sun', '/wellness/public/uploads/photos/photo-1574680096145-d05b474e2155.jpg', 'A therapeutic exfoliation massage that revitalizes skin and relaxes muscles.', '["Salt glow massage combines gentle exfoliation with therapeutic massage to leave skin polished, refreshed, and glowing. Mineral-rich salts buff away dead skin cells while the massage eases muscle tension and stimulates circulation.","It is the perfect way to unwind, detoxify, and leave your skin feeling renewed — a favorite in our wellness programs."]', '[{"title":"Mineral salt exfoliation","definition":"Fine mineral salts gently buff away dead skin cells, leaving skin smooth and renewed. The salt also draws impurities to the surface and stimulates circulation."},{"title":"Therapeutic massage","definition":"Soothing massage strokes relax tense muscles and calm the nervous system. It eases stiffness, encourages deep rest and leaves the whole body feeling lighter."},{"title":"Warm oil application","definition":"Warm, nourishing oil is massaged into the skin to soften, hydrate and protect it. The warmth also helps muscles release more fully and deeply."},{"title":"Circulation-boosting strokes","definition":"Rhythmic, upward strokes encourage blood and lymph to move, carrying oxygen to tissues and waste away from them. Better circulation means glowing skin and renewed energy."},{"title":"Full-body or targeted sessions","definition":"Choose a complete full-body glow or focus on specific areas like the back, legs or shoulders. Every session is shaped around what you need that day."}]', '["Leaves skin soft and renewed","Boosts circulation","Deeply relaxes muscles","Supports gentle detoxification","A luxurious, calming experience"]'),
('chakra-mindfulness-practices', '/special-therapies', 'Chakra Mindfulness Practices', 'icon-moon', '/wellness/public/uploads/photos/photo-1506126613408-eca07ce68773.jpg', 'Meditation and energy practices that bring emotional balance and inner peace.', '["Chakra mindfulness practices blend guided meditation, breathwork, and visualization to harmonize your body&rsquo;s energy centers. These gentle practices help release emotional tension, sharpen focus, and restore a deep sense of calm.","No experience is needed — our guides meet you where you are and lead you through practices that feel nourishing and transformative."]', '[{"title":"Guided meditation","definition":"A guide leads you through gentle meditation that settles the mind and opens awareness. It is a safe, supportive way to begin, whatever your experience."},{"title":"Breathwork techniques","definition":"Conscious breathing patterns calm the nervous system and move energy through the body. These simple techniques can be used anywhere, anytime stress builds."},{"title":"Energy balancing","definition":"Practices that harmonize the body\'s energy centers (chakras), releasing blockages that show up as tension, fatigue or low mood. The result is a renewed sense of flow and ease."},{"title":"Visualization practices","definition":"Guided imagery helps you picture healing energy moving through the body. Visualization deepens relaxation and makes inner states of peace tangible and repeatable."},{"title":"Group and one-on-one sessions","definition":"Practice in the supportive energy of a group or receive personal guidance in a private session. Both formats are adapted to your comfort and goals."}]', '["Promotes emotional balance","Deepens inner peace","Reduces stress and anxiety","Improves focus and clarity","Supports holistic well-being"]'),
('paida-lajin-therapy', '/special-therapies', 'Paida Lajin Therapy', 'icon-activity', '/wellness/public/uploads/photos/photo-1545205597-3d9d02c29597.jpg', 'A traditional healing practice that boosts circulation and flexibility through guided exercise.', '["Paida (guided tapping) and Lajin (stretching) are traditional Chinese healing practices that activate the body&rsquo;s natural repair systems. Gentle, rhythmic tapping stimulates energy flow, while deep stretching keeps tendons and muscles supple.","Performed under the guidance of our therapists, this practice is simple, powerful, and effective for pain, stiffness, and low energy."]', '[{"title":"Guided tapping (Paida)","definition":"Gentle, rhythmic tapping with the palms stimulates energy flow and wakes up the body\'s natural repair systems. It is simple to learn, surprisingly powerful, and can be done anywhere."},{"title":"Deep stretching (Lajin)","definition":"Held, deep stretches lengthen the tendons and muscles, restoring flexibility and relieving stiffness. Stretching regularly keeps the body supple and free of tension."},{"title":"Meridian activation","definition":"Tapping and stretching are directed along the body\'s energy pathways (meridians) to clear blockages and restore smooth flow. This is what gives the practice its deep, systemic effect."},{"title":"Breathing coordination","definition":"Breath is synchronized with each tap and stretch, calming the nervous system and making the practice more effective. Coordinated breathing keeps effort gentle and steady."},{"title":"Progressive home practice","definition":"You are taught a simple daily routine you can continue at home. Regular practice compounds the benefits, keeping circulation, flexibility and energy high between visits."}]', '["Improves circulation","Relieves pain and stiffness","Increases flexibility","Boosts energy and vitality","Easy to practice at home"]'),
('alkaline-water-therapy', '/special-therapies', 'Alkaline Water Therapy', 'icon-droplet', '/wellness/public/uploads/photos/photo-1512290923902-8a9f81dc236c.jpg', 'Structured hydration that supports the body\'s natural balance and detoxification.', '["Proper hydration is the foundation of health, and alkaline water therapy takes it a step further. By raising the body&rsquo;s pH toward a healthier, less acidic state, this simple therapy supports detoxification, digestion, and sustained energy.","We combine pH-balanced water with a guided hydration schedule that fits your daily routine — one of the easiest therapies to integrate into modern life."]', '[{"title":"pH-balanced drinking water","definition":"Structured alkaline water supports a healthier, less acidic internal environment. Drinking it regularly helps the body maintain its natural pH balance and function at its best."},{"title":"Guided hydration schedule","definition":"You receive a simple hydration plan spread across the day, so your body stays consistently and properly hydrated. Timing and quantity are tailored to your routine and needs."},{"title":"Detoxification support","definition":"Steady, adequate hydration helps the kidneys and liver flush waste products more efficiently. It is one of the easiest ways to support the body\'s daily detoxification work."},{"title":"Lifestyle integration tips","definition":"Practical advice on how to weave alkaline hydration into work, travel and daily life. Small habits make the therapy effortless to maintain long-term."},{"title":"Progress monitoring","definition":"Your energy, digestion and hydration are reviewed over time, and the plan is adjusted as needed. Tracking keeps the therapy effective and your results visible."}]', '["Supports natural detoxification","Helps balance body pH","Improves hydration and energy","Aids digestion","Simple to fit into daily life"]'),
('agnihotra-therapy', '/special-therapies', 'Agnihotra Therapy', 'icon-zap', '/wellness/public/uploads/photos/photo-1599901860904-17e6ed7083a0.jpg', 'An ancient fire-based practice that purifies the environment and calms the mind.', '["Agnihotra is an ancient Vedic practice performed at sunrise and sunset, in which herbal offerings are placed into a small fire while specific mantras are chanted. The subtle smoke is believed to purify the air and environment, creating a deeply calming atmosphere.","Many guests find Agnihotra practice remarkably grounding — a daily ritual that reduces stress, improves focus, and adds rhythm to the day."]', '[{"title":"Sunrise and sunset fire ritual","definition":"A small fire is lit at the exact times of sunrise and sunset, following an ancient Vedic ritual. The practice anchors the day with rhythm, intention and a profound sense of calm."},{"title":"Herbal offerings","definition":"Specially prepared herbs, ghee and rice are offered into the fire, releasing a subtle, fragrant smoke. The offerings purify the air and create a serene atmosphere around you."},{"title":"Traditional mantras","definition":"Ancient mantras are chanted as the offerings are made, adding the power of sound to the ritual. Together, fire, herb and sound bring the mind into deep stillness."},{"title":"Guided practice sessions","definition":"Our guides lead the practice step by step, so you learn the correct form and meaning. Guidance makes the ritual accessible and meaningful, whatever your background."},{"title":"Environment purification","definition":"The subtle smoke from the ritual is believed to cleanse the surrounding environment and neutralize pollution. Many guests notice fresher air, fewer allergens and a calmer space."}]', '["Purifies the surrounding environment","Reduces stress and anxiety","Improves focus and clarity","Adds calm daily rhythm","Connects you to ancient tradition"]'),
('weight-nutritional-management', '/special-therapies', 'Weight & Nutritional Management', 'icon-heart', '/wellness/public/uploads/photos/photo-1600334129128-685c5582fd35.jpg', 'A complete program for healthy, sustainable weight loss and balanced nutrition.', '["Weight is about far more than calories — it is about habits, metabolism, nutrition, and mindset. Our program takes a whole-person approach, combining personalized nutrition plans, gentle physical activity, and ongoing support.","The goal is not quick fixes but lasting change: a healthier weight, better energy, and habits you can keep for life."]', '[{"title":"Body composition analysis","definition":"A detailed measurement of body fat, muscle and water gives an honest starting picture. Tracking composition — not just weight — shows real progress and guides the plan."},{"title":"Personalized nutrition plans","definition":"Meal plans are built around your tastes, culture, lifestyle and health needs. Realistic, enjoyable eating is what makes weight loss sustainable."},{"title":"Guided physical activity","definition":"Gentle, structured activity is prescribed at a level your body can safely handle. Movement supports fat loss, boosts metabolism and protects muscle while you slim down."},{"title":"Habit and mindset coaching","definition":"Sustainable weight loss is as much about behavior as biology. Coaching helps you replace old patterns, manage cravings and stay motivated through the journey."},{"title":"Regular progress reviews","definition":"Your results are reviewed at every milestone and the plan is adjusted accordingly. Regular check-ins keep you accountable and celebrating real change."}]', '["Healthy, sustainable weight loss","Balanced, nourishing nutrition","Improved energy and confidence","Lasting habit change","Personal, supportive guidance"]'),
('asthma-care-program', '/special-therapies', 'Asthma Care Program', 'icon-wind', '/wellness/public/uploads/photos/photo-1600880292203-757bb62b4baf.jpg', 'Breathing, yoga, and natural therapies that support easier, calmer breathing.', '["Asthma care goes beyond medication. Our program combines specific breathing exercises, gentle yoga, and natural therapies to strengthen your respiratory system, reduce triggers, and help you breathe with more ease.","Working alongside your medical care, our specialists teach you practical techniques that support lung health and greater confidence in daily life."]', '[{"title":"Therapeutic breathing exercises","definition":"Specific techniques like pursed-lip and diaphragmatic breathing strengthen the respiratory muscles and improve oxygen exchange. Practiced daily, they make breathing feel easier and calmer."},{"title":"Yoga and pranayama","definition":"Gentle yoga postures and controlled breathing open the chest, relax the airways and reduce breathlessness. Regular practice builds lung capacity and respiratory resilience."},{"title":"Natural respiratory remedies","definition":"Herbal steam, warm fluids and natural preparations soothe the airways and loosen mucus. These gentle remedies support easier breathing alongside your medical treatment."},{"title":"Trigger awareness guidance","definition":"You learn to recognize the allergens, pollutants and habits that aggravate your symptoms. Avoiding triggers is one of the most effective ways to prevent flare-ups."},{"title":"Lifestyle support","definition":"Sleep, stress, diet and indoor air all influence asthma. Practical lifestyle adjustments create an environment where your lungs can stay calm and clear."}]', '["Supports easier breathing","Reduces frequency of symptoms","Strengthens respiratory health","Teaches calming breath techniques","Complements medical treatment"]'),
('diabetes-management-program', '/special-therapies', 'Diabetes Management Program', 'icon-activity', '/wellness/public/uploads/photos/photo-1518611012118-696072aa579a.jpg', 'A personalized lifestyle program for healthy blood sugar and lasting energy.', '["Managing diabetes well is about the whole picture: food, movement, stress, and sleep. Our program builds a personalized lifestyle plan that supports healthy blood sugar levels, sustainable weight, and steady energy throughout the day.","Guided by our wellness team and complementary to your medical care, this program empowers you to take confident control of your health."]', '[{"title":"Personalized diet plans","definition":"Meal plans are designed to keep blood sugar steady, balancing carbohydrates, protein and healthy fats. Plans fit your culture and preferences so healthy eating is easy to sustain."},{"title":"Guided physical activity","definition":"Appropriate, enjoyable activity helps muscles use glucose more efficiently and supports healthy weight. Exercise is prescribed safely around your current fitness and health."},{"title":"Stress management practices","definition":"Chronic stress raises blood sugar, so calming the mind is part of the plan. Breathing, meditation and gentle movement keep stress — and glucose — in check."},{"title":"Regular blood sugar awareness","definition":"You learn simple, practical ways to understand how food, activity and stress affect your levels. Self-awareness turns daily numbers into confident health decisions."},{"title":"Progress monitoring and support","definition":"Ongoing reviews track your results and adjust the plan as you improve. Consistent, personal support keeps you motivated and in control of your health."}]', '["Supports healthy blood sugar levels","Promotes steady, lasting energy","Helps with healthy weight management","Builds sustainable healthy habits","Empowering, personal guidance"]');


-- Blog posts (6) — REPLACE = safe to re-import
REPLACE INTO posts (slug, title, category, date, image, excerpt, content, key_points) VALUES
('benefits-of-daily-yoga-practice', 'The Benefits of Daily Yoga Practice', 'Yoga', 'June 12, 2026', '/wellness/public/uploads/photos/photo-1544367567-0f2fcb009e0b.jpg', 'Learn how just 20 minutes of yoga a day improves flexibility, mental health, and overall wellness.', '[{"h":"More Than a Workout","p":"Yoga is often described as exercise, but it is really a complete practice for body and mind. It combines physical postures, controlled breathing, and focused attention — three tools that together lower stress hormones, improve circulation, and build strength in a way that feels good rather than punishing. That is why daily practice, even in small doses, tends to produce changes that last."},{"h":"Flexibility and Strength","p":"A consistent practice gently lengthens tight muscles and strengthens the ones that support good posture. Over weeks, you will notice easier movement in the hips, shoulders, and spine — the areas modern life stiffens most. Unlike heavy gym work, yoga builds functional strength you carry into everyday tasks, from sitting comfortably to bending and lifting with confidence."},{"h":"A Calmer, Clearer Mind","p":"The breathing and meditation elements of yoga train the nervous system to switch from \\"fight or flight\\" to rest and repair. Regular practitioners report better sleep, steadier moods, and a clearer mind under pressure. Studies consistently link yoga with lower anxiety and improved focus, making it one of the most effective drug-free tools for mental wellness we offer."},{"h":"How to Build the Habit","p":"Start small. A daily 20-minute session — a few sun salutations, some standing poses, and five minutes of quiet breathing — is more valuable than a two-hour class once a week. Practice at the same time each day, keep your mat visible, and let consistency, not intensity, be the goal. Our yoga therapists can design a short home sequence that fits your body and schedule."}]', '["Twenty minutes a day is enough to see real change","Consistency matters far more than intensity","The breath is the anchor of every pose","Pair home practice with guided sessions for best results"]'),
('natural-ways-to-boost-immunity', 'Natural Ways to Boost Immunity', 'Nutrition', 'May 28, 2026', '/wellness/public/uploads/photos/photo-1498837167922-ddd27525d352.jpg', 'Discover simple, natural methods to strengthen your immune system and stay healthy all year.', '[{"h":"Immunity Is a Whole-Body System","p":"Your immune system does not live in one organ — it is a network that depends on good nutrition, quality sleep, movement, and low stress. That is good news: it means daily choices, not expensive supplements, are the most powerful way to support it. A body well-fed and well-rested fights off illness far more effectively than one running on empty."},{"h":"Food as Your First Defense","p":"Colorful fruits and vegetables supply the vitamins and antioxidants immune cells need to do their job. Garlic, ginger, turmeric, and citrus are time-tested allies, while fermented foods support the gut — where much of your immune system actually lives. Aim for a rainbow on your plate and let whole foods do the heavy lifting before reaching for pills."},{"h":"Sleep, Movement, and Stress","p":"Sleep is when the immune system does its deepest repair work; seven to eight hours makes a measurable difference. Gentle daily movement keeps circulation and immune cells active, while chronic stress suppresses immunity — which is why our mindfulness and yoga programs are such a natural complement to nutrition advice."},{"h":"Habits That Add Up","p":"Start with one change: an extra serving of vegetables, a consistent bedtime, or a ten-minute walk. Our nutritionists can build a personal immunity plan around your lifestyle, combining diet therapy, herbal support, and movement so the changes become habits rather than resolutions."}]', '["Whole foods beat supplements for immune support","Sleep is when the immune system repairs itself","Chronic stress directly weakens immunity","Start with one habit and build from there"]'),
('managing-stress-through-mindfulness', 'Managing Stress Through Mindfulness', 'Mindfulness', 'May 10, 2026', '/wellness/public/uploads/photos/photo-1506126613408-eca07ce68773.jpg', 'Explore practical techniques for reducing stress and anxiety using breath and presence.', '[{"h":"What Mindfulness Really Is","p":"Mindfulness is not about emptying your mind or reaching a blissful state. It is simply the practice of paying attention to the present moment — the breath, the body, the sounds around you — without judgment. This simple shift interrupts the spiral of worry about the past and future that drives most stress, giving your nervous system a chance to settle."},{"h":"The Breath as an Anchor","p":"Your breath is always with you, which makes it the most reliable anchor for mindfulness. A slow exhale signals safety to the nervous system: inhale for four counts, exhale for six, and repeat for a minute. This single technique can lower a racing heart, ease tension, and create a pause between a stressful moment and your reaction to it."},{"h":"Bringing Mindfulness into the Day","p":"You do not need a meditation cushion to practice. Mindful moments — truly tasting your first sip of tea, feeling your feet on the ground during a walk, noticing your shoulders and letting them drop — accumulate through the day. Over time, these micro-practices retrain attention and make calm your default rather than your exception."},{"h":"A Simple Five-Minute Practice","p":"Find a quiet spot, sit comfortably, and close your eyes. For five minutes, rest your attention on the sensation of breathing. When the mind wanders — and it will — simply notice where it went and return to the breath, without criticism. Our chakra mindfulness and meditation sessions teach this and deeper practices, so you leave with tools you can use anywhere."}]', '["Mindfulness is attention, not emptiness","A longer exhale calms the nervous system","Micro-practices throughout the day add up","Five minutes of daily practice is a real start"]'),
('importance-of-proper-nutrition', 'The Importance of Proper Nutrition', 'Nutrition', 'April 22, 2026', '/wellness/public/uploads/photos/photo-1512621776951-a57141f2eefd.jpg', 'Understand how healthy eating supports long-term health, energy, and disease prevention.', '[{"h":"Food Is Information","p":"Every meal sends signals to your body — about energy, inflammation, repair, and mood. Choose whole foods and your body responds with steady energy, clearer skin, and better digestion. Choose highly processed food and the same signaling drives fatigue, inflammation, and cravings. Nutrition is not about deprivation; it is about the quality of information you give your cells."},{"h":"Building a Balanced Plate","p":"A simple rule covers most needs: fill half your plate with vegetables and fruit, a quarter with whole grains, and a quarter with quality protein such as legumes, eggs, or fish. Add healthy fats — nuts, seeds, olive oil — in small amounts. This template is flexible enough for any cuisine and guarantees the variety your body needs for vitamins, minerals, and fiber."},{"h":"Hydration and Timing","p":"Water is the forgotten nutrient. Mild dehydration shows up as tiredness, headaches, and poor focus long before thirst is noticed. Drink steadily through the day, and eat at regular times — irregular eating stresses blood sugar and digestion. Even small improvements in timing make a noticeable difference in energy and appetite control."},{"h":"Small Changes, Big Results","p":"You do not need a perfect diet overnight. Swap one processed snack for fruit, add a vegetable to dinner, drink a glass of water before each meal. Our diet therapy programs — from raw and bland food plans to fasting support — are built around sustainable change, giving you a structure that turns small steps into lasting transformation."}]', '["Whole foods signal health; processed food signals stress","Half plate vegetables, quarter grains, quarter protein","Hydration affects energy more than most people realize","Sustainable small changes beat perfect short-term diets"]'),
('physiotherapy-for-pain-relief', 'Physiotherapy for Pain Relief', 'Physiotherapy', 'April 05, 2026', '/wellness/public/uploads/photos/photo-1571019613454-1cb2f99b2d8b.jpg', 'How targeted physiotherapy improves mobility, reduces pain, and speeds recovery.', '[{"h":"Pain Is a Signal, Not a Sentence","p":"Pain is your body asking for help, not a verdict that you must simply endure. Many chronic complaints — back ache, stiff neck, knee discomfort — are driven by muscular imbalances and movement patterns that can be corrected. Physiotherapy treats those root causes instead of only masking the symptom, which is why its effects tend to last."},{"h":"How Physiotherapy Works","p":"A physiotherapist starts by assessing how you move: your posture, strength, flexibility, and the way you walk or sit. From that assessment comes a plan that combines hands-on treatment, targeted exercises, and education. Techniques such as manual therapy and electrotherapy relieve pain quickly, while the exercise program builds the strength to keep it away."},{"h":"What a Session Looks Like","p":"Sessions are personal and practical. Expect a mix of gentle manual work, guided movement, and clear homework you can do at home. You will understand your condition in plain language and leave each visit knowing exactly what to practice — because the real progress happens between sessions, with your therapist guiding the way."},{"h":"When to Start","p":"The best time to begin physiotherapy is before pain becomes chronic. If discomfort has lasted more than a few weeks, is limiting daily activities, or keeps returning, an assessment is worth your time. Early intervention shortens recovery and often prevents the problem from becoming a permanent part of life."}]', '["Most chronic pain has a correctable mechanical cause","Assessment comes before treatment — no guesswork","Home exercises are as important as in-clinic sessions","Starting early prevents chronic pain"]'),
('detoxifying-with-natural-therapies', 'Detoxifying with Natural Therapies', 'Therapies', 'March 18, 2026', '/wellness/public/uploads/photos/photo-1519823551278-64ac92734fb1.jpg', 'A gentle, effective guide to natural detox — from hydrotherapy and heat to food and herbs.', '[{"h":"Rethinking Detox","p":"Detox is not about drastic cleanses or punishing fasts. Your body already has sophisticated detox systems in the liver, kidneys, skin, and lungs — the best therapies simply support them. Done gently and consistently, natural detox reduces the load on those systems, improves energy, and leaves skin and digestion feeling renewed."},{"h":"Water, Heat, and Movement","p":"Hydrotherapy uses warm and cool water to stimulate circulation and the lymphatic system, which carries waste away from tissues. Steam and sauna open the skin, the body\'s largest elimination organ, while gentle movement keeps lymph flowing. These simple, pleasant therapies are the backbone of every detox program we design."},{"h":"Food and Herbs That Help","p":"Detox-friendly eating means lots of water, fiber-rich vegetables, and foods that support the liver — leafy greens, beets, lemon, and turmeric. Herbal support with gentle botanicals adds another layer. Our diet therapy plans make detox nourishing rather than austere, so you feel energized instead of depleted."},{"h":"Supporting Your Body\'s Own Detox","p":"The most powerful detox tool is one you control daily: quality sleep, hydration, and reducing stress. Specialized programs — like supervised therapeutic fasting, alkaline water therapy, and salt glow massage — accelerate the process when you need a deeper reset. Our team will design a program matched to your goals and comfort."}]', '["Detox means supporting your body, not punishing it","Water, heat, and movement are the foundation","Liver-friendly foods and botanicals add real support","Sleep and stress management are the hidden keys"]');


-- Gallery items (8)
REPLACE INTO gallery (id, title, description, image, alt, sort_order) VALUES
('1', 'Wellness Facilities', 'Peaceful spaces designed for healing and relaxation.', '/wellness/public/uploads/photos/photo-1544161515-4ab6ce6db874.jpg', 'Peaceful wellness spa facilities', '1'),
('2', 'Yoga Sessions', 'Gentle and therapeutic yoga programs for every age.', '/wellness/public/uploads/photos/photo-1545205597-3d9d02c29597.jpg', 'Guided yoga session', '2'),
('3', 'Physiotherapy Treatments', 'Professional care for mobility, injury recovery, and pain relief.', '/wellness/public/uploads/photos/photo-1571019613454-1cb2f99b2d8b.jpg', 'Physiotherapy treatment session', '3'),
('4', 'Therapy Rooms', 'Clean, modern spaces equipped for natural therapies.', '/wellness/public/uploads/photos/photo-1519823551278-64ac92734fb1.jpg', 'Modern therapy room', '4'),
('5', 'Organic Farms', 'Fresh produce and botanicals used in healing programs.', '/wellness/public/uploads/photos/photo-1466692476868-aef1dfb1e735.jpg', 'Fresh organic farm produce', '5'),
('6', 'Workshops & Seminars', 'Educational events focused on wellness and healthy living.', '/wellness/public/uploads/photos/photo-1543269865-cbf427effbad.jpg', 'Wellness workshop with participants', '6'),
('7', 'Patient Activities', 'Community sessions that encourage healthy routines.', '/wellness/public/uploads/photos/photo-1544367567-0f2fcb009e0b.jpg', 'Patients practicing together', '7'),
('8', 'Meditation Spaces', 'Calm environments for mindfulness and inner balance.', '/wellness/public/uploads/photos/photo-1506126613408-eca07ce68773.jpg', 'Calm meditation space', '8');


-- Testimonials (3)
REPLACE INTO testimonials (id, name, role, initials, avatar, rating, quote, sort_order) VALUES
('1', 'Sunita Pradhan', 'Physiotherapy Patient', 'SP', 'a1', '5', 'After months of chronic back pain, the physiotherapy and yoga programs here changed my life. I feel stronger and pain-free for the first time in years.', '1'),
('2', 'Anita Rana', 'Diet Therapy Patient', 'AR', 'a2', '5', 'The diet therapy program was completely personalized. The nutritionists guided me step by step, and my energy levels have never been better.', '2'),
('3', 'Manoj Karki', 'Mindfulness Program', 'MK', 'a3', '5', 'A peaceful, professional environment. The meditation and mindfulness practices helped me manage stress and sleep better than I ever expected.', '3');


-- Team members (6)
REPLACE INTO team (id, name, role, initials, avatar, sort_order) VALUES
('1', 'Dr. Rajesh Sharma', 'Founder & Holistic Medicine Specialist', 'RS', 'a1', '1'),
('2', 'Dr. Meena Gurung', 'Naturopathy Specialist', 'MG', 'a2', '2'),
('3', 'Anil Thapa', 'Senior Physiotherapist', 'AT', 'a3', '3'),
('4', 'Sita Adhikari', 'Yoga Therapist', 'SA', 'a4', '4'),
('5', 'Nirmala K.C.', 'Nutritionist', 'NK', 'a5', '5'),
('6', 'Prakash Shrestha', 'Wellness Consultant', 'PS', 'a6', '6');


-- Tariff plans (3)
REPLACE INTO tariff_plans (id, name, description, price, period, features, featured, badge, cta_label, sort_order) VALUES
('1', 'Daily Wellness', 'Perfect for busy days — drop in for a single therapy session.', '$25', 'session', '["Any single therapy of your choice","Complimentary consultation","Flexible scheduling"]', '0', '', 'Book a Session', '1'),
('2', '7-Day Wellness Retreat', 'A full immersive week of healing, detox, and daily therapies.', '$140', 'week', '["Daily therapy sessions","Yoga & meditation classes","Personalized diet plan","Priority scheduling"]', '1', 'Most Popular', 'Book the Retreat', '2'),
('3', '30-Day Transformation', 'A month-long guided program for lasting lifestyle change.', '$480', 'month', '["Weekly consultations","Full therapy schedule","Nutrition & fitness coaching","Progress tracking & reports"]', '0', '', 'Start Your Journey', '3');


-- Tariff services (7)
REPLACE INTO tariff_services (id, service, duration, price, sort_order) VALUES
('1', 'Initial Consultation', '30 Minutes', '$20', '1'),
('2', 'Yoga Session', '1 Hour', '$15', '2'),
('3', 'Physiotherapy', '1 Hour', '$25', '3'),
('4', 'Acupuncture', '45 Minutes', '$30', '4'),
('5', 'Naturopathy Treatment', '1 Hour', '$35', '5'),
('6', 'Diet Consultation', '45 Minutes', '$20', '6'),
('7', 'Special Therapy', '1 Hour', '$40', '7');


-- Why Choose Us feature cards (5)
REPLACE INTO features (id, title, description, image, icon, sort_order) VALUES
('1', 'Expert Healthcare Team', 'Doctors, physiotherapists, yoga instructors, and nutritionists collaborate for complete care.', '/wellness/public/uploads/photos/photo-1576091160399-112ba8d25d1d.jpg', 'icon-users', '1'),
('2', 'Personalized Treatment Plans', 'Every patient receives a custom program based on their health condition and lifestyle.', '/wellness/public/uploads/photos/photo-1544161515-4ab6ce6db874.jpg', 'icon-heart', '2'),
('3', 'Natural Healing Methods', 'We focus on drug-free treatments that activate the body\'s own self-healing abilities.', '/wellness/public/uploads/photos/photo-1519823551278-64ac92734fb1.jpg', 'icon-leaf', '3'),
('4', 'Modern Facilities', 'Modern therapy equipment blends seamlessly with tried-and-tested traditional methods.', '/wellness/public/uploads/photos/photo-1506126613408-eca07ce68773.jpg', 'icon-shield', '4'),
('5', 'Holistic Wellness', 'We nurture your physical, mental, emotional, and spiritual balance together.', '/wellness/public/uploads/photos/photo-1545205597-3d9d02c29597.jpg', 'icon-sun', '5');


-- What We Offer cards (6)
REPLACE INTO offers (id, title, description, image, icon, link, sort_order) VALUES
('1', 'Naturopathy', 'Natural treatments that detoxify the body, boost immunity, and restore balance.', '/wellness/public/uploads/photos/photo-1466692476868-aef1dfb1e735.jpg', 'icon-leaf', '/treatments', '1'),
('2', 'Yoga & Meditation', 'Improve flexibility, mental peace, and emotional balance through mindful practice.', '/wellness/public/uploads/photos/photo-1545205597-3d9d02c29597.jpg', 'icon-moon', '/treatments', '2'),
('3', 'Physiotherapy', 'Restore mobility, strength, and physical function after injury or illness.', '/wellness/public/uploads/photos/photo-1576091160399-112ba8d25d1d.jpg', 'icon-activity', '/physiotherapy', '3'),
('4', 'Diet Therapy', 'Nutritional programs crafted for healing, detoxification, and healthy living.', '/wellness/public/uploads/photos/photo-1512621776951-a57141f2eefd.jpg', 'icon-droplet', '/diet-therapy', '4'),
('5', 'Special Therapies', 'Unique therapies for relaxation, detoxification, and disease management.', '/wellness/public/uploads/photos/photo-1571019613454-1cb2f99b2d8b.jpg', 'icon-sun', '/special-therapies', '5'),
('6', 'Acupuncture', 'Targeted stimulation to restore energy flow, relieve pain, and calm the mind.', '/wellness/public/uploads/photos/photo-1512290923902-8a9f81dc236c.jpg', 'icon-zap', '/treatments', '6');


-- Editable page sections (40) — includes the home stats band (15+ / 10K+ / 25+ / 40+)
REPLACE INTO page_sections (page_key, section_key, kicker, heading, content, sub_content, image, media, link, link_label, extras) VALUES
('site', 'brand', '', 'Chitrawan Nature Cure Hospital', '', '', '', '', '', '', '[]'),
('site', 'topbar', 'Sun – Fri: 8:00 AM – 7:00 PM', '', '', 'nchchitwan@gmail.com', '', '', '+977 56-535213', '', '[]'),
('site', 'nav', '', '', '', '', '', '', '', '', '[]'),
('site', 'footer', 'Sun – Fri: 8 AM – 7 PM
Sat: 9 AM – 4 PM', 'Chitrawan Nature Cure Hospital, Bharatpur-15, Nepal', 'Where ancient healing traditions meet modern therapeutic practices. We help you achieve physical, mental, and emotional balance through personalized natural care.', 'nchchitwan@gmail.com', '', '', '+977 56-535213', 'Healing naturally, living fully.', '["Facebook | #","Instagram | #","TikTok | #"]'),
('home', 'hero', 'Natural Healing · Holistic Care', 'Rejuvenate Your Body, Mind & Soul', 'Welcome to Chitrawan Nature Cure Hospital, where ancient healing traditions meet modern therapeutic practices. Our team helps you achieve physical, mental, and emotional balance with personalized natural care.', '4.9/5 rated by 1,200+ happy patients', '', 'Olive and White Modern Spa and Wellness Banner Landscape.mp4', '', '', '["Book an Appointment|/contact|primary","Explore Our Programs|/treatments|light"]'),
('home', 'stats', '', '', '', '', '', '', '', '', '["15+|Years of Experience","10K+|Happy Patients","25+|Expert Therapists","40+|Natural Therapies"]'),
('home', 'about_intro', 'About Chitrawan', 'Healing Naturally, Living Fully', 'Chitrawan Nature Cure Hospital is a holistic healthcare destination committed to promoting natural healing and preventive healthcare. Our peaceful environment, expert practitioners, and evidence-based therapies help patients restore balance and improve their quality of life.', 'Since 2010|Healing with care & compassion', '/wellness/public/uploads/photos/photo-1545205597-3d9d02c29597.jpg', '', '/about', 'More About Us', '["Treating the root cause, not just symptoms","Personalized plans for every patient","Traditional wisdom meets modern science","A calm, natural environment for healing"]'),
('home', 'why', 'Why Choose Us', 'Care That Puts You First', 'Reasons patients trust us with their wellness journey.', '', '', '', '', '', '[]'),
('home', 'offers', 'What We Offer', 'Our Core Services', 'A complete range of natural therapies, designed to support your health at every stage.', '', '', '', '', '', '[]'),
('home', 'testimonials', 'Patient Stories', 'What Our Patients Say', 'Real experiences from people who found their balance with us.', '', '', '', '', '', '[]'),
('home', 'story', 'Our Story', 'A Journey of Healing, Growing with Every Patient', 'Chitrawan Nature Cure Hospital was born from a simple belief: true health comes from within. What began as a small clinic with two therapists has grown into a trusted wellness destination, guided every step of the way by the thousands of patients who trusted us with their care.

Every therapy we offer, every space we design, and every team member we welcome reflects the same promise — to treat you as family and walk beside you on your path to balance.', '12+ Years|Of natural healing', '/wellness/public/uploads/photos/photo-1512621776951-a57141f2eefd.jpg', '', '/about', 'Read Our Full Story', '["Founded on natural, drug-free healing","Thousands of patients helped since 2010","A caring team that treats you like family"]'),
('home', 'cta', 'Start Your Journey', 'Ready to Begin Your Wellness Journey?', 'Book an appointment today and take the first step toward a healthier, more balanced you.', '', '', '', '', '', '["Book an Appointment|/contact|primary","View Tariff|/tariff|light"]'),
('about', 'hero', '', 'About Us', 'Meet the people and philosophy behind Chitrawan Nature Cure Hospital — where natural healing is a way of life.', '', '', '', '', '', '[]'),
('about', 'founder', '01 · Our Founders', 'Meet Our Founders', 'Dr. Rajesh Sharma established Chitrawan Nature Cure Hospital with the vision of creating a healthcare facility that promotes natural healing and healthy living. With more than twenty years of experience in holistic medicine, he believes prevention and lifestyle changes are the keys to long-term wellness.

His mission is to help people heal naturally and live healthier lives through personalized care and compassionate treatment.', 'Dr. Rajesh Sharma|Founder & Holistic Medicine Specialist', '/wellness/public/uploads/photos/photo-1576091160399-112ba8d25d1d.jpg', '', '', '', '["Dr. Sunita Sharma|Co-Founder & Yoga Therapy Director|/wellness/public/uploads/photos/photo-1545205597-3d9d02c29597.jpg|Dr. Sunita Sharma co-founded Chitrawan Nature Cure Hospital with a vision of combining classical yoga therapy with modern natural medicine. She leads the yoga and mindfulness programs and has guided thousands of patients toward calmer, healthier lives."]'),
('about', 'approach', '02 · Our Approach', 'Treating the Root Cause', 'Our approach focuses on treating the root cause of diseases rather than simply managing symptoms. We believe true healing occurs when the body, mind, and spirit are in harmony.', '', '/wellness/public/uploads/photos/photo-1544161515-4ab6ce6db874.jpg', '', '', '', '["Natural healing without harmful side effects","Prevention of disease through lifestyle change","Personalized care for every individual","Healthy nutrition as the foundation of health","Physical, mental, and emotional wellness"]'),
('about', 'doctors', '03 · Our Doctors', 'Our Doctors & Specialists', 'A multidisciplinary team working together for your complete care.', '', '', '', '', '', '["Dr. Meena Gurung|Naturopathy Specialist|/wellness/public/uploads/photos/photo-1543269865-cbf427effbad.jpg","Anil Thapa|Senior Physiotherapist|/wellness/public/uploads/photos/photo-1571019613454-1cb2f99b2d8b.jpg","Sita Adhikari|Yoga Therapist|/wellness/public/uploads/photos/photo-1512290923902-8a9f81dc236c.jpg","Nirmala K.C.|Nutritionist|/wellness/public/uploads/photos/photo-1498837167922-ddd27525d352.jpg","Prakash Shrestha|Wellness Consultant|/wellness/public/uploads/photos/photo-1466692476868-aef1dfb1e735.jpg"]'),
('about', 'vision', '06 · Our Vision', 'Our Vision', '', '', '/wellness/public/uploads/photos/photo-1519823551278-64ac92734fb1.jpg', '', '', '', '["Where We Are Headed|To become a leading center for holistic healthcare by promoting natural healing, preventive medicine, and healthy living practices worldwide.|icon-sun"]'),
('about', 'mission', '04 · Our Mission', 'Our Mission', 'The promises we make to every patient who walks through our doors.', 'What We Are Committed To', '/wellness/public/uploads/photos/photo-1506126613408-eca07ce68773.jpg', '', '', '', '["Provide high-quality natural healthcare services","Promote preventive healthcare and wellness education","Empower individuals to take control of their health","Create awareness about healthy living","Combine traditional wisdom with modern science"]'),
('about', 'group', '05 · Our Group', 'Our Group', 'The people who make Chitrawan Nature Cure Hospital a place of healing.', '', '/wellness/public/uploads/photos/photo-1544367567-0f2fcb009e0b.jpg', '', '', '', '[]'),
('about', 'cta', 'Work With Us', 'Experience Care That Listens', 'Meet our doctors and begin a wellness plan designed around you.', '', '', '', '', '', '["Book an Appointment|/contact|primary","Our Treatments|/treatments|light"]'),
('contact', 'hero', '', 'Contact Us', 'We would love to hear from you. Reach out or book your appointment today.', '', '', '', '', '', '[]'),
('contact', 'info', 'Reach Us', 'Contact Information', '', '', '', '', '', '', '["Our Address|Chitrawan Nature Cure Hospital, Bharatpur-15, Nepal","Phone|+977 56-535213","Email|nchchitwan@gmail.com","Opening Hours|Sunday – Friday: 8:00 AM – 7:00 PM\\nSaturday: 9:00 AM – 4:00 PM"]'),
('contact', 'form', '', 'Book an Appointment', 'Fill in your details and our team will confirm your booking shortly.', '', '', '', '', '', '[]'),
('contact', 'map', 'Find Us', 'Our Location', 'Chitrawan Nature Cure Hospital · Bharatpur-15, Nepal', '', '', '', 'Chitrawan Nature Cure Hospital, Bharatpur-15, Nepal', '', '[]'),
('treatments', 'hero', '', 'Treatments', 'Explore our signature natural therapies, each designed to help your body heal itself.', '', '', '', '', '', '[]'),
('treatments', 'cta', 'Not Sure Where to Start?', 'Talk to Our Wellness Team', 'Get a free consultation and let us recommend the right therapy for you.', '', '', '', '', '', '["Book a Consultation|/contact|primary","View Tariff|/tariff|light"]'),
('physiotherapy', 'hero', '', 'Physiotherapy', 'Rebuild strength, restore mobility, and live pain-free with expert-guided therapy.', '', '', '', '', '', '[]'),
('physiotherapy', 'cta', 'Move Better, Live Better', 'Restore Your Body’s Full Potential', 'Book a physiotherapy assessment and get a personalized recovery plan.', '', '', '', '', '', '["Book a Session|/contact|primary","View Tariff|/tariff|light"]'),
('diet', 'hero', '', 'Diet Therapy', 'Food is medicine. Discover nutritional programs tailored to your body and goals.', '', '', '', '', '', '[]'),
('diet', 'cta', 'Food Is Medicine', 'Let Nutrition Transform Your Health', 'Get a personalized diet plan built around your body, lifestyle, and goals.', '', '', '', '', '', '["Book a Consultation|/contact|primary","View Tariff|/tariff|light"]'),
('special', 'hero', '', 'Special Therapies', 'Unique, time-honored therapies for relaxation, detoxification, and disease management.', '', '', '', '', '', '[]'),
('special', 'cta', 'Something Unique', 'Find the Therapy That Fits You', 'Ask our team about special programs and personalized treatment plans.', '', '', '', '', '', '["Ask Our Team|/contact|primary","View Tariff|/tariff|light"]'),
('tariff', 'hero', '', 'Tariff', 'Transparent pricing and flexible packages for every wellness journey.', '', '', '', '', '', '[]'),
('tariff', 'packages', 'Pricing', 'Wellness Packages', 'Simple, transparent pricing for every stage of your journey.', '', '', '', '', '', '[]'),
('tariff', 'services', 'Rate Card', 'Individual Service Prices', 'All sessions include a personal assessment with your therapist.', 'Prices are indicative. Please contact us for the latest offers and package discounts.', '', '', '', '', '[]'),
('tariff', 'qr', 'Advance Payment', 'Pay Your Advance by QR Code', 'Secure your package or appointment with a small advance payment. Scan the QR code with any UPI payment app, then submit your details with the payment screenshot below.', 'UPI ID: chitrawan naturecure@upi', '', '', '', 'Keep your payment reference number — it helps us verify your payment faster.', '["Scan the QR code with your UPI / payment app","Enter the advance amount shown in the package above","Fill in the form with your details and attach the payment screenshot"]'),
('gallery', 'hero', '', 'Gallery', 'A glimpse into our healing spaces, therapies, and community.', '', '', '', '', '', '[]'),
('blog', 'hero', '', 'Blog', 'Insights, tips, and stories to support your path to better health.', '', '', '', '', '', '[]'),
('blog', 'cta', 'Have a Question?', 'Get Advice from Our Team', 'Our specialists are happy to answer your wellness questions in person or by phone.', '', '', '', '', '', '["Contact Us|/contact|primary"]'),
('therapy', 'cta', 'Ready When You Are', 'Begin Your {title} Journey', 'Book a session today — our team will guide you every step of the way.', '', '', '', '', '', '["Book an Appointment|/contact|primary","All {catLabel}|{catUrl}|light"]'),
('post', 'cta', 'Put It Into Practice', 'Ready to Feel the Difference?', 'Talk to our wellness team about a program tailored to you — from yoga and nutrition to physiotherapy and natural detox.', '', '', '', '', '', '["Book a Consultation|/contact|primary","More Articles|/blog|light"]');


-- Default admin user (admin / Admin@Chitrawan2026 — CHANGE IT after first login!).
-- Inserted only when no admin exists, so re-imports never overwrite your login.
INSERT INTO admin_users (username, password_hash, display_name, created_at, updated_at)
SELECT 'admin', '$2y$12$63sa9N1sIy5j2UvJjLC0Bu9weR.fossZMbQZg4TCto2T0/kgzn.ym', 'Administrator', NOW(), NOW() FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_users);


-- ============================== END OF DUMP ==============================
