<?php
/**
 * Daily-use backup script.
 *
 * Exports the whole `wellness` MySQL database to a timestamped .sql file under
 * storage/backups/ so you always have a restorable copy of your content,
 * appointments, team, posts, etc.
 *
 * Usage (from the project root):
 *   php app/scripts/backup.php
 *
 * Automate daily (every day at 2am — adjust the path):
 *   0 2 * * * /Applications/XAMPP/xamppfiles/bin/php /Applications/XAMPP/xamppfiles/htdocs/wellness/app/scripts/backup.php >> /tmp/wellness-backup.log 2>&1
 *
 * The storage/backups/ folder is git-ignored (private data). Old backups are
 * pruned automatically, keeping the newest BACKUP_KEEP (default 14).
 */

require_once __DIR__ . '/../core/Dotenv.php';
Dotenv::load(dirname(__DIR__, 2) . '/.env');

require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../core/Database.php';

define('BACKUP_KEEP', 14);

$dir = APP_ROOT . '/storage/backups';
if (!is_dir($dir)) {
    @mkdir($dir, 0777, true);
}

$stamp = date('Y-m-d-Hi');
$pdo = Database::pdo();

if ($pdo === null) {
    fwrite(STDERR, "[backup] MySQL unavailable — nothing to back up.\n");
    exit(1);
}

$file = $dir . '/wellness-' . $stamp . '.sql';
$fh = fopen($file, 'w');
if ($fh === false) {
    fwrite(STDERR, "[backup] Cannot write " . $file . "\n");
    exit(1);
}

fwrite($fh, "-- Chitrawan Nature Cure Hospital backup " . date('Y-m-d H:i:s') . "\n");
fwrite($fh, "-- Generated by app/scripts/backup.php\n\n");
fwrite($fh, "SET NAMES utf8mb4;\n\n");

$tableCount = 0;
try {
    $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
    foreach ($tables as $table) {
        $table = (string) $table;

        // 1. Schema.
        $create = $pdo->query('SHOW CREATE TABLE `' . $table . '`')->fetch(PDO::FETCH_ASSOC);
        $createSql = $create['Create Table'] ?? '';
        fwrite($fh, "DROP TABLE IF EXISTS `" . $table . "`;\n");
        fwrite($fh, $createSql . ";\n\n");

        // 2. Rows.
        $rows = $pdo->query('SELECT * FROM `' . $table . '`')->fetchAll();
        foreach ($rows as $row) {
            $values = array_map(static function ($v) use ($pdo) {
                if ($v === null) {
                    return 'NULL';
                }

                return $pdo->quote((string) $v);
            }, array_values($row));
            fwrite($fh, "INSERT INTO `" . $table . "` VALUES (" . implode(', ', $values) . ");\n");
        }
        fwrite($fh, "\n");
        $tableCount++;
    }
} catch (Throwable $e) {
    fwrite(STDERR, "[backup] Export failed: " . $e->getMessage() . "\n");
    fclose($fh);
    @unlink($file);
    exit(1);
}

fclose($fh);
$size = is_file($file) ? (int) filesize($file) : 0;
echo "[backup] Saved " . $file . " (" . $tableCount . " tables, " . round($size / 1024, 1) . " KB)\n";

// Prune old backups, keep the newest BACKUP_KEEP.
$backups = glob($dir . '/wellness-*.sql') ?: [];
usort($backups, 'strcmp'); // timestamped names sort oldest → newest
while (count($backups) > BACKUP_KEEP) {
    $old = array_shift($backups);
    @unlink($old);
    echo "[backup] Pruned old backup: " . basename((string) $old) . "\n";
}

exit(0);
